apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: default
  source:
    chart: jaeger
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 0.71.16
    helm:
      values: |
        provisionDataStore:
          cassandra: false
          elasticsearch: true
        storage:
          type: elasticsearch
        elasticsearch:
          host: elasticsearch-master
          port: 9200
        collector:
          service:
            type: ClusterIP
        query:
          service:
            type: ClusterIP
        agent:
          enabled: true
        allInOne:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 