apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.36.3
    helm:
      values: |
        loki:
          auth_enabled: false
        singleBinary:
          replicas: 1
        monitoring:
          selfMonitoring:
            enabled: false
          lokiCanary:
            enabled: false
        persistence:
          enabled: true
          size: 10Gi
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 