apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  project: default
  source:
    chart: opentelemetry-collector
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.72.0
    helm:
      values: |
        mode: deployment
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
            prometheus:
              config:
                scrape_configs:
                  - job_name: 'kubernetes-pods'
                    kubernetes_sd_configs:
                      - role: pod
                    relabel_configs:
                      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                        action: keep
                        regex: true
          processors:
            batch:
              timeout: 10s
            memory_limiter:
              check_interval: 5s
              limit_mib: 1000
              spike_limit_mib: 200
          exporters:
            logging:
              loglevel: debug
            otlp:
              endpoint: jaeger-collector:4317
              tls:
                insecure: true
            prometheus:
              endpoint: 0.0.0.0:8889
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [otlp, logging]
              metrics:
                receivers: [otlp, prometheus]
                processors: [memory_limiter, batch]
                exporters: [prometheus, logging]
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 